spring:
  application:
    name: b-service

server:
  port: 8002
  servlet:
    session:
      timeout: 7200
      cookie:
        name: msf-session-id
    encoding:
      charset: UTF-8
    context-path: /b-service
  compression:
    enabled: true
  tomcat:
    uri-encoding: UTF-8
  error:
    whitelabel:
      enabled: false
    path: /error
