server:
  port: 8000
---
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: a-service-svc
          uri: http://localhost:8001/
          predicates:
            - Path=/a-service/**
          filters:
            - name: AServiceFilter
              args:
                baseMessage: Spring Cloud Gateway A-ServiceFilter
                preLogger: true
                postLogger: true
        - id: b-service-svc
          uri: http://localhost:8002/
          predicates:
            - Path=/b-service/**
          filters:
            - name: BServiceFilter
              args:
                baseMessage: Spring Cloud Gateway B-ServiceFilter
                preLogger: true
                postLogger: true


# application.yml
otel:
  service:
    name: gateway-service
  traces:
    exporter: jaeger
    jaeger:
      endpoint: http://localhost:14250
  resource:
    attributes:
      service.name: gateway-service
